[package]
name = "cless"
version = "0.1.0"
authors = ["Mo Yuli <moyuli@sensetime.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
ncurses = "5"
